#!/bin/sh
set -eu
sjail=$(realpath "$0")

freebsd_url=https://download.freebsd.org/releases/amd64/amd64/
# Not strictly necessary. zroot nowadays is created with compress=lz4 atime=off
# and these are inherited by sub-datasets. This could still be useful when the
# dataset in not on zroot. See
# https://cgit.freebsd.org/src/tree/usr.sbin/bsdinstall/scripts/zfsboot?h=releng/14.1#n54
zfs_options="-o compress=lz4 -o atime=off"

. /usr/local/etc/sjail.conf
. /usr/local/share/sjail/common.sh

sjail_init() {
    log "Setting up sjail"

    if [ ! -e /usr/local/etc/sjail.conf ]; then
        log_fatal "missing /usr/local/etc/sjail.conf"
    fi

    zfs create ${zfs_options} -o mountpoint=${zfs_mount} "${zfs_dataset}"

    # recipes arbitrarily in sjail pool
    zfs create -p "${zfs_dataset}/recipes"

    if ! grep -q '.include "'${zfs_mount}/jails /etc/jail.conf 2> /dev/null; then
        cat <<EOF >> /etc/jail.conf
.include "${zfs_mount}/jails/*/jail.conf";
EOF
    fi

    sysrc_silent jail_enable="YES"
    sysrc_silent jail_parallel_start="YES"
}

sjail_release_create() {
    local version="$1"
    local nofetch=$(arg_get nofetch "$@")

    log "Creating release ${version}"

    local release_path="${zfs_mount}/releases/${version}"
    if [ -e "${release_path}" ]; then
        log_fatal "$version already fetched"
    fi

    zfs create -p "${zfs_dataset}/releases/${version}"

    if [ -z "${nofetch}" ]; then
        fetch "${freebsd_url}/${version}/MANIFEST" -o /tmp/MANIFEST
    fi

    local release_archives="base" a
    for a in ${release_archives}; do
        local archive="${a}.txz"

        if [ -z "${nofetch}" ]; then
            rm -f /tmp/${archive} || true
            fetch "${freebsd_url}/${version}/${archive}" -o /tmp/${archive}
        fi

        local checksum_want=$(grep -w ${archive} /tmp/MANIFEST | cut -f2)
        local checksum_got=$(sha256 -q /tmp/${archive})
        if [ "${checksum_got}" != "${checksum_want}" ]; then
            log_fatal "wrong checksum for ${archive}: ${checksum_got}"
        fi

        tar -xf /tmp/${archive} -C "${release_path}"
    done
}

sjail_release_update() {
    local version="$1"
    log "Updating release ${version}"
    freebsd-update --currently-running ${version} -b ${zfs_mount}/releases/${version} fetch install
    # TODO uncomment when code stabilizes
    #freebsd-update --currently-running ${version} -b ${zfs_mount}/releases/${version} IDS
}

# Only to avoid destroying a release on which some jails depend.
sjail_release_destroy() {
    local version="$1"
    log "Destroying release ${version}"

    local release_path="${zfs_mount}/releases/${version}"
    if grep -qs -w "${release_path}" ${zfs_mount}/jails/*/fstab; then
        log_fatal "${version} still in use"
    fi

    zfs destroy "${zfs_dataset}/releases/${version}"
}

sjail_create() {
    local jail_name="$1"; shift
    local version="$1"; shift
    local ip4=$(arg_get ip4 "$@")
    local ip6=$(arg_get ip6 "$@")
    local nat=$(arg_get nat "$@")
    local rdr=$(arg_get rdr "$@")
    log "Creating thin jail: $jail_name"

    zfs create -p "${zfs_dataset}/jails/${jail_name}"

    local jail_path="${zfs_mount}/jails/${jail_name}"
    cat <<EOF > ${jail_path}/fstab
${zfs_mount}/releases/${version} ${jail_path}/root/.ro nullfs ro 0 0
EOF

    local ip4_addr=""
    if [ -n "${ip4}" ]; then
        ip4_addr="ip4.addr = ${ip4};"
    fi
    local ip6_addr=""
    local ip6_mode="ip6 = disable;"
    if [ -n "${ip6}" ]; then
        ip6_addr="ip6.addr = ${ip6};"
        ip6_mode="ip6 = new;"
    fi

    # Cloned loopback network setup
    if [ "$(printf %.2s ${interface})" = "lo" ]; then
        nat=${nat:-1}
        rdr=${rdr:-1}
    fi
    # TODO use jail metadata when they're available
    # https://people.freebsd.org/~dch/posts/2025-01-12-jail-metadata/
    echo jail_meta_nat="${nat}" >> "${jail_path}/meta.conf"
    echo jail_meta_rdr="${rdr}" >> "${jail_path}/meta.conf"

    local hooks="
  exec.poststart += \"${sjail} _hook_start \$name\";
  exec.prestop   += \"${sjail} _hook_stop \$name\";
"

    local jail_path_in_conf="${zfs_mount}/jails/\$name"
    cat << EOF > "${jail_path}/jail.conf"
${jail_name} {
  host.hostname = \$name;
  path = ${jail_path_in_conf}/root;

  exec.clean;
  exec.consolelog = ${jail_path_in_conf}/console.log;
  exec.start = '/bin/sh /etc/rc';
  exec.stop = '/bin/sh /etc/rc.shutdown';
  exec.prestart  += "cp /etc/resolv.conf \$path/etc/resolv.conf";
  exec.prestart  += "cp /etc/localtime \$path/etc";
  ${hooks}
  exec.poststop  += "rm \$path/etc/resolv.conf";
  exec.poststop  += "rm \$path/etc/localtime";

  mount.devfs;
  mount.fstab = ${jail_path_in_conf}/fstab;
  enforce_statfs = 2;
  devfs_ruleset = 4;

  securelevel = 2;

  interface = ${interface};
  ${ip4_addr}
  ${ip6_addr}
  ${ip6_mode}
}
EOF

    mkdir "${jail_path}/root"
    cd "${jail_path}/root"

    mkdir .ro
    mkdir usr
    local ro="bin boot lib libexec rescue sbin usr/bin usr/include usr/lib usr/lib32 usr/libdata usr/libexec usr/sbin usr/share usr/src" l
    for l in ${ro}; do
      ln -Fsf /.ro/${l} ${l}
    done

    local rw=".cshrc .profile COPYRIGHT dev etc media mnt net proc root tmp var usr/obj usr/tests" files
    for files in ${rw}; do
      cp -a "${zfs_mount}/releases/${version}/${files}" "${jail_path}/root/${files}"
    done

    # minor adjustments
    mkdir -p usr/home
    ln -s usr/home home
    touch etc/fstab

    cd -

    sysrc_silent jail_list+="${jail_name}"
}

sjail_destroy() {
    local jail_name="$1"
    log "Destroying thin jail: $jail_name"

    if jls -j ${jail_name} >/dev/null 2>&1; then
        log_fatal "jail running. Stop first."
    fi

    zfs destroy -r "${zfs_dataset}/jails/${jail_name}"

    sysrc_silent jail_list-="${jail_name}"
}

sjail_list() {
    local format="%-10s %-8s %-13s %-15s %3s\n"
    printf "${format}" Name Status Release Path

    local running=$(jls -N | tail -n +2 | cut -d' ' -f2)
    local ftabs=$(grep -h -s "${zfs_mount}/releases/" ${zfs_mount}/jails/*/fstab)
    local conf
    jail -e'`' | sort | while read conf; do
        local jail=$(echo "${conf}" | jail_conf_get_val name)
        local status=$(echo "${running}" | grep -w "${jail}")
        if [ -n "${status}" ]; then
            status=Up
        else
            status=Down
        fi

        local release=$(echo -e "${ftabs}" | awk -F'/' '/\/'"${jail}"'\//{print$4}')
        if [ -z "${release}" ]; then
            release=-
        fi

        local path=$(echo "${conf}" | jail_conf_get_val path)

        printf "${format}" ${jail} ${status} ${release} ${path}
    done
}

sjail_apply() {
    local jail_name="$1"
    local recipe_name="$2"
    log "Applying recipe ${2} on ${1}"

    local jail_path="${zfs_mount}/jails/${jail_name}"

    if ! jls -j ${jail_name} >/dev/null 2>&1; then
        log_fatal "jail must be running. Start first."
    fi

    local recipe_path="${zfs_mount}/recipes/${recipe_name}/apply.sh"
    if [ ! -e "${recipe_path}" ]; then
        log_fatal "recipe not found: ${recipe_path}"
    fi

    . /usr/local/share/sjail/cmd.sh
    local needs_restart=0
    . "${recipe_path}"

    if [ ${needs_restart} -gt 0 ];then
        jail -rc ${jail_name}
        log "[${jail_name}] ${HLINE} JAIL RESTARTED ${HLINE}"
    fi
}


# Additional jail start operations
sjail_hook_start() {
    local jail_name="$1"
    local jail_path="${zfs_mount}/jails/${jail_name}"

    . "${jail_path}/meta.conf"

    if [ "${jail_meta_nat}" = "1" ]; then
        local ip4s=$(jail_conf_get_ips "${jail_name}" ip4)
        local ip6s=$(jail_conf_get_ips "${jail_name}" ip6)
        local ip
        for ip in ${ip4s} ${ip6s}; do
            pfctl -q -t jails -T add "${ip}"
        done
    fi

    if [ "${jail_meta_rdr}" = "1" -a -s "${jail_path}/rdr.conf" ]; then
        while read line; do
            line=$(echo "${line}") # trim
            [ ${#line} -eq 0 -o \
              "$(printf %.1s "${line}")" = "#" ] && continue
            pf_rdr_add "$jail_name" ${line}
        done < "${jail_path}/rdr.conf"
    fi
}

# Additional jail stop operations
sjail_hook_stop() {
    local jail_name="$1"
    local jail_path="${zfs_mount}/jails/${jail_name}"

    . "${jail_path}/meta.conf"

    if [ "${jail_meta_nat}" = "1" ]; then
        local ip4s=$(jail_conf_get_ips "${jail_name}" ip4)
        local ip6s=$(jail_conf_get_ips "${jail_name}" ip6)
        local ip
        for ip in ${ip4s} ${ip6s}; do
            pfctl -q -t jails -T delete "${ip}"
        done
    fi

    if [ "${jail_meta_rdr}" = "1" ]; then
        pf_rdr_clear "${jail_name}"
    fi
}

pf_rdr_add() {
    local jail_name=$1 proto=$2 host_port=$3 jail_port=$4

    local ext_if=$(prop_get ${pf_ext_if} /etc/pf.conf)

    # Taking the first ip for redirection by convention.
    local jail_ip4=$(jail_conf_get_ips "${jail_name}" ip4 | cut -d" " -f1)
    if [ -n "$jail_ip4" ]; then
        ( pfctl -a "rdr/${jail_name}" -Psn 2> /dev/null; # previous
          echo "rdr pass on ${ext_if} inet proto ${proto}" \
               "to port ${host_port} -> ${jail_ip4} port ${jail_port}" ) \
            | pfctl -a "rdr/${jail_name}" -f-
    fi

    local jail_ip6=$(jail_conf_get_ips "${jail_name}" ip6 | cut -d" " -f1)
    if [ -n "$jail_ip6" ]; then
        ( pfctl -a "rdr/${jail_name}" -Psn 2> /dev/null; # previous
          echo "rdr pass on ${ext_if} inet6 proto ${proto}" \
               "to port ${host_port} -> ${jail_ip6} port ${jail_port}" ) \
            | pfctl -a "rdr/${jail_name}" -f-
    fi
}

pf_rdr_clear() {
    local jail_name=$1
    pfctl -a "rdr/${jail_name}" -Fn
}


usage() {
    cat <<EOF
Usage: `basename $0` [-hv] command [args]

Options:
    -h   help; show this help.
    -v   verbose; show more information.

Commands:
    apply        Apply recipe on jail. Args: name recipe
    create       Create thin jail from base image. Args: name version.
                 Opts: ip4, ip6, nat, rdr
    destroy      Destroy thin jail. Args: name
    init         Setup zpool, sysrc, networking.
    list         List status of all jails.
    rel-create   Fetch and create base image. Args: version
                 (e.g. 14.2-RELEASE). Opts: nofetch=1 skips download.
    rel-destroy  Destroy base image. Args: version
    rel-update   Apply freebsd-update on base image with version.
                 Can be done anytime. Args: version
    version      Show version.
EOF
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

case "$1" in
    help|-h|--help)
        usage
        exit 0
        ;;
    version|--version)
        . /usr/local/share/sjail/version.sh
        echo "${SJAIL_VERSION}"
        exit 0
        ;;
    -v)
        log_debug() {
            log "  $*"
        }
        shift
        ;;
esac

if [ "$(id -u)" -ne 0 ]; then
    log_fatal "not root"
fi

command=${1}; shift
case $command in
    init)
        sjail_init
        ;;
    rel-create)
        sjail_release_create "$@"
        ;;
    rel-update)
        sjail_release_update "$@"
        ;;
    rel-destroy)
        sjail_release_destroy "$@"
        ;;
    create)
        sjail_create "$@"
        ;;
    destroy)
        sjail_destroy "$@"
        ;;
    list)
        sjail_list
        ;;
    apply)
        sjail_apply "$@"
        ;;
    _hook_start)
        sjail_hook_start "$@"
        ;;
    _hook_stop)
        sjail_hook_stop "$@"
        ;;
    *)
        usage
        ;;
esac
